# Generated by Django 4.2.2 on 2025-01-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_mailing_owner_recipient_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="first_sending",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Начало рассылки"
            ),
        ),
    ]
